services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: note_template_lab
    ports:
      - "5432:5432"
    volumes:
      - note_template_lab_db:/var/lib/postgresql/data

volumes:
  note_template_lab_db:
