"use client";

import { useMemo, useState } from "react";

type TranscriptLine = {
  start: number;
  duration: number;
  text: string;
};

type TrackInfo = {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
};

type TranscriptResult = {
  videoId: string;
  title: string | null;
  author: string | null;
  lengthSeconds: number | null;
  availableTracks: TrackInfo[];
  usedTrack: TrackInfo;
  lines: TranscriptLine[];
  plainText: string;
  withTimestamps: string;
};

function formatTimestamp(seconds: number): string {
  const total = Math.floor(seconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (n: number) => n.toString().padStart(2, "0");
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

export default function Home() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<TranscriptResult | null>(null);
  const [showTimestamps, setShowTimestamps] = useState(true);
  const [copied, setCopied] = useState(false);

  const displayText = useMemo(() => {
    if (!result) return "";
    return showTimestamps ? result.withTimestamps : result.plainText;
  }, [result, showTimestamps]);

  async function fetchTranscript(lang?: string) {
    if (!url.trim()) {
      setError("YouTubeのURLを入力してください。");
      return;
    }
    setLoading(true);
    setError(null);
    setCopied(false);
    try {
      const res = await fetch("/api/transcript", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url, lang }),
      });
      const data = await res.json();
      if (!res.ok) {
        setResult(null);
        setError(data.error ?? "文字起こしの取得に失敗しました。");
        return;
      }
      setResult(data);
    } catch {
      setResult(null);
      setError("通信エラーが発生しました。ネットワーク接続を確認してください。");
    } finally {
      setLoading(false);
    }
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    fetchTranscript();
  }

  async function handleCopy() {
    if (!displayText) return;
    await navigator.clipboard.writeText(displayText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleDownload() {
    if (!result) return;
    const blob = new Blob([displayText], { type: "text/plain;charset=utf-8" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${result.title ?? result.videoId}.txt`;
    link.click();
    URL.revokeObjectURL(link.href);
  }

  return (
    <main className="flex-1 flex flex-col items-center px-4 py-10">
      <div className="w-full max-w-3xl">
        <header className="text-center mb-8">
          <h1 className="text-3xl font-bold mb-2">YouTube文字起こしツール</h1>
          <p className="text-foreground/70">
            YouTube動画のURLを入力すると、字幕から文字起こしを取得します
          </p>
        </header>

        <form
          onSubmit={handleSubmit}
          className="bg-panel border border-border rounded-2xl p-6 shadow-sm mb-6"
        >
          <label htmlFor="url" className="block font-semibold mb-2">
            YouTube動画のURL
          </label>
          <div className="flex flex-col sm:flex-row gap-3">
            <input
              id="url"
              type="text"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="https://www.youtube.com/watch?v=..."
              className="flex-1 border border-border rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-accent"
            />
            <button
              type="submit"
              disabled={loading}
              className="bg-accent hover:bg-accent-dark disabled:opacity-50 text-white font-semibold px-6 py-3 rounded-lg transition-colors cursor-pointer disabled:cursor-not-allowed"
            >
              {loading ? "取得中..." : "文字起こしする"}
            </button>
          </div>
          {error && (
            <p className="text-accent-dark mt-3 text-sm whitespace-pre-wrap">{error}</p>
          )}
        </form>

        {result && (
          <div className="bg-panel border border-border rounded-2xl p-6 shadow-sm">
            <div className="mb-4">
              <h2 className="text-xl font-bold">{result.title ?? result.videoId}</h2>
              {result.author && (
                <p className="text-foreground/60 text-sm">{result.author}</p>
              )}
            </div>

            <div className="flex flex-wrap items-center gap-3 mb-4">
              {result.availableTracks.length > 1 && (
                <select
                  value={result.usedTrack.languageCode}
                  onChange={(e) => fetchTranscript(e.target.value)}
                  className="border border-border rounded-lg px-3 py-2 text-sm"
                >
                  {result.availableTracks.map((t) => (
                    <option key={t.languageCode} value={t.languageCode}>
                      {t.name}
                      {t.isAutoGenerated ? "（自動生成）" : ""}
                    </option>
                  ))}
                </select>
              )}

              <label className="flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={showTimestamps}
                  onChange={(e) => setShowTimestamps(e.target.checked)}
                />
                タイムスタンプを表示
              </label>

              <div className="flex-1" />

              <button
                onClick={handleCopy}
                className="border border-border rounded-lg px-4 py-2 text-sm font-medium hover:bg-background cursor-pointer"
              >
                {copied ? "コピーしました" : "コピー"}
              </button>
              <button
                onClick={handleDownload}
                className="border border-border rounded-lg px-4 py-2 text-sm font-medium hover:bg-background cursor-pointer"
              >
                ダウンロード (.txt)
              </button>
            </div>

            <div className="max-h-[500px] overflow-y-auto border border-border rounded-lg">
              {showTimestamps ? (
                <ul className="divide-y divide-border">
                  {result.lines.map((line, i) => (
                    <li key={i} className="flex gap-3 px-4 py-2 text-sm">
                      <span className="text-accent-dark font-mono shrink-0">
                        {formatTimestamp(line.start)}
                      </span>
                      <span>{line.text}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="px-4 py-3 text-sm leading-relaxed whitespace-pre-wrap">
                  {result.plainText}
                </p>
              )}
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
