import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";

type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
};

type TranscriptLine = {
  start: number;
  duration: number;
  text: string;
};

const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

function extractVideoId(input: string): string | null {
  const trimmed = input.trim();

  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) {
    return trimmed;
  }

  try {
    const url = new URL(trimmed);
    const host = url.hostname.replace(/^www\./, "");

    if (host === "youtu.be") {
      const id = url.pathname.slice(1).split("/")[0];
      return id || null;
    }

    if (host === "youtube.com" || host === "m.youtube.com" || host === "music.youtube.com") {
      if (url.pathname === "/watch") {
        return url.searchParams.get("v");
      }
      const shortsMatch = url.pathname.match(/^\/shorts\/([a-zA-Z0-9_-]{11})/);
      if (shortsMatch) return shortsMatch[1];
      const embedMatch = url.pathname.match(/^\/embed\/([a-zA-Z0-9_-]{11})/);
      if (embedMatch) return embedMatch[1];
      const liveMatch = url.pathname.match(/^\/live\/([a-zA-Z0-9_-]{11})/);
      if (liveMatch) return liveMatch[1];
    }
  } catch {
    return null;
  }

  return null;
}

async function fetchWatchPageHtml(videoId: string): Promise<string> {
  const res = await fetch(
    `https://www.youtube.com/watch?v=${videoId}&hl=ja&has_verified=1`,
    {
      headers: {
        "User-Agent": USER_AGENT,
        "Accept-Language": "ja,en-US;q=0.9,en;q=0.8",
      },
      cache: "no-store",
    }
  );

  if (!res.ok) {
    throw new Error(`動画ページの取得に失敗しました (HTTP ${res.status})`);
  }

  return res.text();
}

function extractPlayerResponse(html: string): Record<string, unknown> {
  const match = html.match(/ytInitialPlayerResponse\s*=\s*(\{[\s\S]+?\});/);
  if (!match) {
    throw new Error("動画情報の解析に失敗しました。非公開または削除された動画の可能性があります。");
  }
  try {
    return JSON.parse(match[1]);
  } catch {
    throw new Error("動画情報のJSON解析に失敗しました。");
  }
}

function getCaptionTracks(playerResponse: Record<string, unknown>): CaptionTrack[] {
  const captions = playerResponse.captions as
    | {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: Array<{
            baseUrl: string;
            languageCode: string;
            kind?: string;
            name?: { simpleText?: string };
          }>;
        };
      }
    | undefined;

  const rawTracks =
    captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];

  return rawTracks.map((track) => ({
    baseUrl: track.baseUrl,
    languageCode: track.languageCode,
    name: track.name?.simpleText ?? track.languageCode,
    isAutoGenerated: track.kind === "asr",
  }));
}

function pickTrack(tracks: CaptionTrack[], preferredLang?: string): CaptionTrack | null {
  if (tracks.length === 0) return null;
  if (preferredLang) {
    const exact = tracks.find((t) => t.languageCode === preferredLang);
    if (exact) return exact;
  }
  const ja = tracks.find((t) => t.languageCode === "ja" || t.languageCode.startsWith("ja-"));
  if (ja) return ja;
  const en = tracks.find((t) => t.languageCode === "en" || t.languageCode.startsWith("en-"));
  if (en) return en;
  return tracks[0];
}

async function fetchTranscriptLines(track: CaptionTrack): Promise<TranscriptLine[]> {
  const url = new URL(track.baseUrl);
  url.searchParams.set("fmt", "json3");

  const res = await fetch(url.toString(), {
    headers: {
      "User-Agent": USER_AGENT,
      "Accept-Language": "ja,en-US;q=0.9,en;q=0.8",
    },
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error(`字幕データの取得に失敗しました (HTTP ${res.status})`);
  }

  const data = (await res.json()) as {
    events?: Array<{
      tStartMs?: number;
      dDurationMs?: number;
      segs?: Array<{ utf8?: string }>;
    }>;
  };

  const lines: TranscriptLine[] = [];
  for (const event of data.events ?? []) {
    if (!event.segs) continue;
    const text = event.segs
      .map((seg) => seg.utf8 ?? "")
      .join("")
      .replace(/\n/g, " ")
      .trim();
    if (!text) continue;
    lines.push({
      start: (event.tStartMs ?? 0) / 1000,
      duration: (event.dDurationMs ?? 0) / 1000,
      text,
    });
  }
  return lines;
}

function formatTimestamp(seconds: number): string {
  const total = Math.floor(seconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (n: number) => n.toString().padStart(2, "0");
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

export async function POST(req: NextRequest) {
  let body: { url?: string; lang?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "リクエストの形式が不正です。" }, { status: 400 });
  }

  const rawUrl = body.url?.trim();
  if (!rawUrl) {
    return NextResponse.json({ error: "YouTubeのURLを入力してください。" }, { status: 400 });
  }

  const videoId = extractVideoId(rawUrl);
  if (!videoId) {
    return NextResponse.json(
      { error: "有効なYouTubeのURLまたは動画IDを入力してください。" },
      { status: 400 }
    );
  }

  try {
    const html = await fetchWatchPageHtml(videoId);
    const playerResponse = extractPlayerResponse(html);

    const playability = playerResponse.playabilityStatus as
      | { status?: string; reason?: string }
      | undefined;
    if (playability && playability.status && playability.status !== "OK") {
      return NextResponse.json(
        {
          error: `この動画は取得できません（${playability.reason ?? playability.status}）。`,
        },
        { status: 422 }
      );
    }

    const videoDetails = playerResponse.videoDetails as
      | { title?: string; author?: string; lengthSeconds?: string }
      | undefined;

    const tracks = getCaptionTracks(playerResponse);
    if (tracks.length === 0) {
      return NextResponse.json(
        { error: "この動画には字幕（文字起こし）データが見つかりませんでした。" },
        { status: 404 }
      );
    }

    const selected = pickTrack(tracks, body.lang);
    if (!selected) {
      return NextResponse.json(
        { error: "字幕データの選択に失敗しました。" },
        { status: 404 }
      );
    }

    const lines = await fetchTranscriptLines(selected);
    if (lines.length === 0) {
      return NextResponse.json(
        { error: "字幕データが空でした。別の言語を試してください。" },
        { status: 404 }
      );
    }

    const plainText = lines.map((l) => l.text).join(" ");
    const withTimestamps = lines
      .map((l) => `[${formatTimestamp(l.start)}] ${l.text}`)
      .join("\n");

    return NextResponse.json({
      videoId,
      title: videoDetails?.title ?? null,
      author: videoDetails?.author ?? null,
      lengthSeconds: videoDetails?.lengthSeconds
        ? Number(videoDetails.lengthSeconds)
        : null,
      availableTracks: tracks.map((t) => ({
        languageCode: t.languageCode,
        name: t.name,
        isAutoGenerated: t.isAutoGenerated,
      })),
      usedTrack: {
        languageCode: selected.languageCode,
        name: selected.name,
        isAutoGenerated: selected.isAutoGenerated,
      },
      lines,
      plainText,
      withTimestamps,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "文字起こしの取得中にエラーが発生しました。";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
